name: Docker

on:
  push:
    branches: main
    paths:
      - 'docker/**'
      - '.github/workflows/build-docker-image.yml'
  workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: amd64
          - os: ubuntu-22.04-arm
            platform: arm64
    runs-on: ${{matrix.os}}
    timeout-minutes: 120
    concurrency:
      group: ${{matrix.os}}-${{ github.ref }}-docker
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write
    steps:
        # 4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        # 3.10.0
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

      - name: Login to ghcr.io
        # 3.4.0
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the image
        # 6.15.0
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: docker
          file: docker/Dockerfile
          platforms: linux/${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          no-cache-filters: image
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}-${{ matrix.platform }}
            ghcr.io/${{ github.repository }}:latest-${{ matrix.platform }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-manifest:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - docker
    concurrency:
      group: ${{ github.ref }}-docker_manifest
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write
    steps:
        # 4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Login to ghcr.io
        # 3.4.0
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          docker manifest create \
            ghcr.io/${{ github.repository }}:${{ github.sha }} \
            --amend ghcr.io/${{ github.repository }}:${{ github.sha }}-amd64 \
            --amend ghcr.io/${{ github.repository }}:${{ github.sha }}-arm64

          docker manifest push ghcr.io/${{ github.repository }}:${{ github.sha }}

          docker manifest create \
            ghcr.io/${{ github.repository }}:latest \
            --amend ghcr.io/${{ github.repository }}:${{ github.sha }}-amd64 \
            --amend ghcr.io/${{ github.repository }}:${{ github.sha }}-arm64

          docker manifest push ghcr.io/${{ github.repository }}:latest
