name: Test reproducibility

on:
  push:
    branches: main
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'docker/**'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/flathub-infra/reproducibility-tests:latest
      options: --privileged
    permissions:
      contents: read
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
        # 4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Run check on com.google.Chrome
        continue-on-error: true
        run: flathub-repro-checker --appid com.google.Chrome

      - name: Upload result of com.google.Chrome
        # 4.6.2
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: diffoscope-com.google.Chrome-${{ github.sha }}-${{ github.run_id }}-${{ github.job }}-${{ github.run_attempt }}
          path: ./diffoscope_result-com.google.Chrome

      - name: Run check on com.discordapp.Discord
        continue-on-error: true
        run: flathub-repro-checker --appid com.discordapp.Discord

      - name: Upload result of com.discordapp.Discord
        # 4.6.2
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: diffoscope-com.discordapp.Discord-${{ github.sha }}-${{ github.run_id }}-${{ github.job }}-${{ github.run_attempt }}
          path: ./diffoscope_result-com.discordapp.Discord

      - name: Run check on com.brave.Browser
        continue-on-error: true
        run: flathub-repro-checker --appid com.brave.Browser

      - name: Upload result of com.brave.Browser
        # 4.6.2
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: diffoscope-com.brave.Browser-${{ github.sha }}-${{ github.run_id }}-${{ github.job }}-${{ github.run_attempt }}
          path: ./diffoscope_result-com.brave.Browser

      - name: Run check on org.vinegarhq.Sober
        continue-on-error: true
        run: flathub-repro-checker --appid org.vinegarhq.Sober

      - name: Upload result of org.vinegarhq.Sober
        # 4.6.2
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: diffoscope-org.vinegarhq.Sober-${{ github.sha }}-${{ github.run_id }}-${{ github.job }}-${{ github.run_attempt }}
          path: ./diffoscope_result-org.vinegarhq.Sober

      - name: Run check on com.valvesoftware.Steam
        continue-on-error: true
        run: flathub-repro-checker --appid com.valvesoftware.Steam

      - name: Upload result of com.valvesoftware.Steam
        # 4.6.2
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: diffoscope-com.valvesoftware.Steam-${{ github.sha }}-${{ github.run_id }}-${{ github.job }}-${{ github.run_attempt }}
          path: ./diffoscope_result-com.valvesoftware.Steam

      - name: Run check on com.spotify.Client
        continue-on-error: true
        run: flathub-repro-checker --appid com.spotify.Client

      - name: Upload result of com.spotify.Client
        # 4.6.2
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: diffoscope-com.spotify.Client-${{ github.sha }}-${{ github.run_id }}-${{ github.job }}-${{ github.run_attempt }}
          path: ./diffoscope_result-com.spotify.Client
