name: Test reproducibility

on:
  push:
    branches: main
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'docker/**'
  workflow_dispatch:

env:
  IMAGE: ghcr.io/flathub-infra/flatpak-builder-lint:unprivileged

jobs:
  ci:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Free up disk space
        if: false
        run: |
          sudo swapoff -a || true
          sudo rm -rf /opt/ghc /usr/local/.ghcup || true
          sudo rm -rf /opt/hostedtoolcache/CodeQL || true
          sudo rm -rf /opt/hostedtoolcache/PyPy
          sudo rm -rf /usr/share/gradle-*
          sudo rm -rf /usr/local/julia* /usr/share/java /usr/share/kotlinc
          sudo rm -rf /opt/hostedtoolcache/go /opt/az /opt/microsoft /opt/pipx
          sudo rm -rf /usr/share/miniconda /home/runner/.rustup /home/packer/.rustup /home/runneradmin/.rustup
          sudo rm -rf /etc/skel/.rustup /opt/hostedtoolcache/node /opt/google-cloud-sdk
          sudo rm -rf /usr/share/az_* /opt/google /usr/lib/firefox /usr/local/aws-*
          sudo rm -rf /usr/libexec/gcc /opt/actionarchivecache /opt/hostedtoolcache/Ruby
          sudo rm -rf /var/lib/mysql /usr/local/n
          sudo rm -rf /swapfile || true
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet /usr/share/swift
          sudo rm -rf /usr/local/share/boost /usr/local/share/powershell
          sudo rm -rf /usr/lib/google-cloud-sdk /usr/lib/jvm
          sudo rm -rf /usr/local/graalvm /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/lib/dotnet /usr/lib/php /usr/share/mysql
          sudo rm -rf /usr/lib/llvm-*
          sudo rm -rf /usr/lib/mono
          sudo apt-get clean || true
          sudo rm -rf /var/lib/apt/lists/*

      - name: Enable unprivileged user namespaces
        run: |
          sudo aa-teardown >/dev/null 2>&1 || true
          sudo systemctl disable --now apparmor.service >/dev/null 2>&1
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Create work directory
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/reproworkdir
          mkdir -p ${GITHUB_WORKSPACE}/reproworkdir/tmp
          chmod -R 777 ${GITHUB_WORKSPACE}/reproworkdir

      - name: Download seccomp profile
        run: curl -s https://raw.githubusercontent.com/flathub-infra/vorarbeiter/refs/heads/main/flatpak.seccomp.json -o flatpak.seccomp.json

      - name: Run checks
        continue-on-error: true
        run: |
          run_check() {
            APPID="$1"
            docker run --rm \
              --entrypoint="" \
              --security-opt seccomp=${GITHUB_WORKSPACE}/flatpak.seccomp.json \
              --security-opt apparmor=unconfined \
              --cap-drop all \
              -v /proc:/host/proc \
              -v "${GITHUB_WORKSPACE}/reproworkdir:/reproworkdir" \
              -e TMPDIR=/reproworkdir/tmp \
              -e GITHUB_SERVER_URL \
              -e GITHUB_REPOSITORY \
              -e GITHUB_RUN_ID \
              -w /reproworkdir \
              ${{ env.IMAGE }} \
              flathub-repro-checker --json --appid "$APPID"
          }

          run_check io.bassi.Amberol

      - name: Upload results
        # 4.6.2
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: diffoscope-results-${{ github.sha }}-${{ github.run_id }}-${{ github.job }}-${{ github.run_attempt }}
          path: ./reproworkdir/diffoscope_result-*
