name: Test reproducibility

on:
  push:
    branches: main
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'docker/**'
  workflow_dispatch:

env:
  IMAGE: ghcr.io/flathub-infra/reproducibility-tests:latest

jobs:
  ci:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Create work directory
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/reproworkdir
          chmod -R 777 ${GITHUB_WORKSPACE}/reproworkdir

      - name: Run checks
        continue-on-error: true
        run: |
          run_check() {
            APPID="$1"
            docker run --rm \
              --privileged \
              --entrypoint="" \
              -v "${GITHUB_WORKSPACE}/reproworkdir:/reproworkdir" \
              -w /reproworkdir \
              ${{ env.IMAGE }} \
              flathub-repro-checker --appid "$APPID" || true
          }

          run_check org.kde.okular
          run_check org.prismlauncher.PrismLauncher
          run_check com.ranfdev.DistroShelf
          run_check io.missioncenter.MissionCenter
          run_check org.kde.filelight
          run_check org.kde.kcalc


      - name: Upload results
        # 4.6.2
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: diffoscope-results-${{ github.sha }}-${{ github.run_id }}-${{ github.job }}-${{ github.run_attempt }}
          path: ./reproworkdir/diffoscope_result-*
